name: Deploy

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      COMPOSER_PROCESS_TIMEOUT: 0
      COMPOSER_NO_INTERACTION: 1
      COMPOSER_NO_AUDIT: 1
      HOME_USER: ${{ secrets.HOME_USER }}
      VPS_HOST: ${{ secrets.VPS_HOST }}
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install Composer dependencies (local build)
        run: composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Generate Application Key
        run: php artisan key:generate --force

      - name: Set Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Build Frontend Assets
        run: |
          npm ci
          npm run build

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Deploy to Home Server via reverse tunnel
        run: |
          ssh -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              -p 2222 \
              "$HOME_USER@$VPS_HOST" "
                cd $DEPLOY_PATH &&
                git pull origin main &&
                composer install --no-dev --optimize-autoloader &&
                php artisan migrate --force &&
                php artisan config:cache &&
                php artisan route:cache
              "
