name: Deploy

on:
  push:
    branches:
      - main  # deploy only from main branch

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Install Composer dependencies
      run: composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Generate Application Key
      run: php artisan key:generate --force

    - name: Set Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Build Frontend Assets
      run: |
        npm ci
        npm run build

    - name: Deploy to Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      run: |
        echo "$SSH_PRIVATE_KEY" > key.pem
        chmod 600 key.pem
        rsync -avz --exclude='.env' --exclude='node_modules' --exclude='vendor' ./ $SERVER_USER@$SERVER_HOST:$DEPLOY_PATH
        ssh -i key.pem $SERVER_USER@$SERVER_HOST "cd $DEPLOY_PATH && composer install --no-dev --optimize-autoloader && php artisan migrate --force && php artisan cache:clear && php artisan config:cache"
